version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: counter-app-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: counter-app-go
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    restart: unless-stopped

volumes:
  pg_data: