services:
  app:
    image: golang:1.25-rc-bookworm
    working_dir: /app
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    command: sh -c "go mod download && go run ./cmd/app/main.go"
    depends_on:
      - postgres

volumes:
  go-cache: